#! /bin/sh

# Autostart programs
nitrogen --restore &

# kill previous panel
kill -9 KILL $(pgrep lemonbar)
kill -9 KILL $(pgrep panel)
# run panel
panel &

# Monitor setup
# bspc monitor -d 1 2 3 4 5 6 7 8 9
bspc monitor eDP1  -d 1 2 3 4 5 6 7 8 9
bspc monitor HDMI1 -d 1 2 3 4 5 6 7 8 9

# Config
bspc config border_width         2
bspc config window_gap           10

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config focused_border_color	"#FCAF2B"

# Rules

## If refreshed, remove prev rules, to prevent doubling.
bspc rule -r "*" 

bspc rule -a firefox state=floating rectangle=1024x600+200+100 #desktop='2.local' # follow=on 
bspc rule -a Sxiv state=floating
bspc rule -a KeePassXC state=floating
bspc rule -a XFontSel state=floating
bspc rule -a BAZECOR state=floating rectangle=1024x600+200+100

