#!/bin/sh
# Use dmenu to read manuals in pdf's.
# Somehow some man pages are not shown in man -k .
# If full manpage name is written out and passed to std,
# then the manpage will appear.

man -k . | dmenu -i -l 5 | awk '{print $1}' | xargs -r man -Tpdf | zathura - &
