#!/bin/zsh

# Script to open file using fzf.
# Additional, give $1 as a starting path, 
# default is $HOME (ie when $1 is empty).
# Eg. use with floating_app script.

# DEPENDENCIES: 
# * fzf, rg, fd
# * env variables for different program types.

# $1 is directory. If it's empty, $HOME is used.

exclude=".git|.mozilla|.cache|.npm|.cargo|.ghc|.stack|.local|.pki|.pylint.d|ipython|.jupyter" 

# +i is case insensitive
open=$(fd --hidden --type f . $1 | rg -v $exclude | fzf +i)

if [[ -z $open ]]
then
  echo "No file chosen"
elif [[ -n $(echo $open | rg ".pdf") ]]
then
	eval $(echo "$READER $open")
elif [[ -n $(echo $open | rg ".jpg|.jpeg|.png") ]]
then
	eval $(echo "$IMAGES $open")
elif [[ -n $(echo $open | rg ".mp3|.mp4") ]] 
then
	eval $(echo "$MEDIA $open")
else
	eval $(echo "$EDITOR $open")
fi
