#!/bin/sh
# when calling the script, need to prepend '.'
# for example `. <cmd> <filter>
# also print out the dir, if forgot to prepend the dot so can just copy paste the full path if necessary, or use the value itself.
# $1 search from where
# $2 filter
test -z "$1" && echo "incorrect first argument: expected path" && exit 1
filter=$(test -z "$2" && echo ".*/Documents.*\|.*/Downloads.*\|.*/Music.*\|.*/Videos.*\|.*/Books.*\|.*/go/src.*\|.*/\.scripts.*\|.*/\.config.*" || echo ".*/.*$2.*")
p=$(find "$1" \
	-regextype sed -iregex ".*/\.git.*\|.*/chromium.*" -prune \
	-o -regextype sed -iregex "$filter" \
	-type d \
	-print | fzf)
echo "$p"
test "$p" && cd "$p"
