#!/bin/sh
# when calling the script, need to prepend '.'
# for example `. <cmd> <filter>
# also print out the dir, if forgot to prepend the dot so can just copy paste the full path if necessary, or use the value itself.
filter=$(test -z "$1" && echo ".*/Documents.*\|.*/Downloads.*\|.*/go/src.*\|.*/\.scripts.*\|.*/\.config.*" || echo ".*/.*$1.*")
open=$(find $(pwd) \
	-regextype sed -iregex ".*/\.git.*\|.*/tags\|.*/.*\.swp\|.*/.*\.swo" -prune \
	-o -regextype sed -iregex "$filter" \
	-type f \
	-print | fzf --prompt="$(pwd) > ") 
test "$open" && xdg-open "$open" && echo "$open"
